apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: pushup-api
  namespace: pushups
  annotations:
    traefik.ingress.kubernetes.io/router.entrypoints: web
spec:
  ingressClassName: traefik
  rules:
  - host: pushups.wire.mattjewell.co.uk
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: pushup-api
            port:
              number: 80
