apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - namespace.yaml
  - deployment.yaml
  - service.yaml
  - auth-secrets.yaml
  - ollama-secret.yaml
  - ingress.yaml
  - argocd-app.yaml
