import { Hono } from 'hono';
import { createDatabase } from '../src/db.js';
import { workoutRoutes } from '../src/routes/workouts.js';
import { planningRoutes } from '../src/routes/planning.js';
import { authRoutes } from '../src/routes/auth.js';
import { bearerAuth } from '../src/middleware/bearerAuth.js';

const AUTH_SECRET = 'rbac-test-secret-32-bytes-or-thereabouts';
const REGISTER_KEY = 'rbac-test-register-key';

// Mock fetch so the planning route's Ollama call returns a deterministic
// payload without network access. Each call returns the same shape.
const fakeOllamaPlan = JSON.stringify({
  dailyTargets: { mon: 10, tue: 10, wed: 10, thu: 10, fri: 10, sat: 10, sun: 5 },
  notes: 'test plan',
});

beforeEach(() => {
  (global as { fetch: unknown }).fetch = jest.fn().mockResolvedValue({
    ok: true,
    json: async () => ({ response: fakeOllamaPlan }),
  });
});

function buildApp() {
  const db = createDatabase(':memory:');
  const app = new Hono();
  app.route('/auth', authRoutes(AUTH_SECRET, REGISTER_KEY));
  app.use('/api/*', bearerAuth(AUTH_SECRET));
  app.route('/api/v1/workouts', workoutRoutes(db));
  app.route('/api/v1/plan', planningRoutes(db, 'http://ollama.invalid', 'fake-model'));
  return { app, db };
}

async function register(app: Hono): Promise<{ token: string; deviceId: string }> {
  const res = await app.request('/auth/register', {
    method: 'POST',
    headers: { 'Content-Type': 'application/json' },
    body: JSON.stringify({ registerKey: REGISTER_KEY }),
  });
  expect(res.status).toBe(200);
  return res.json() as Promise<{ token: string; deviceId: string }>;
}

function makeSession(id: string, startedAt: string) {
  return {
    id,
    exerciseId: 'pushups',
    weeklyPlanId: null,
    sessionType: 'regular',
    targetReps: 20,
    startedAt,
    endedAt: startedAt,
    totalReps: 25,
    setCount: 2,
    userFeedback: null,
    sets: [
      { id: `${id}-s1`, setNumber: 1, reps: 12, recordedAt: startedAt, restSeconds: 60 },
      { id: `${id}-s2`, setNumber: 2, reps: 13, recordedAt: startedAt, restSeconds: null },
    ],
  };
}

async function authedJson(app: Hono, path: string, token: string, body?: unknown) {
  return app.request(path, {
    method: 'POST',
    headers: { 'Content-Type': 'application/json', Authorization: `Bearer ${token}` },
    body: JSON.stringify(body ?? {}),
  });
}

async function authedGet(app: Hono, path: string, token: string) {
  return app.request(path, {
    method: 'GET',
    headers: { Authorization: `Bearer ${token}` },
  });
}

describe('RBAC: per-device data scoping', () => {
  it('a session synced as A is invisible to B in /stats', async () => {
    const { app } = buildApp();
    const a = await register(app);
    const b = await register(app);
    expect(a.deviceId).not.toBe(b.deviceId);

    // A syncs a session well within the 7-day stats window.
    const startedAt = new Date(Date.now() - 6 * 60 * 60 * 1000).toISOString();
    const syncRes = await authedJson(app, '/api/v1/workouts/sync', a.token, {
      sessions: [makeSession('sess-a-1', startedAt)],
    });
    expect(syncRes.status).toBe(200);
    expect(await syncRes.json()).toEqual({ synced: ['sess-a-1'] });

    // B fetches /stats and must see nothing.
    const bStats = await authedGet(app, '/api/v1/workouts/stats', b.token);
    expect(bStats.status).toBe(200);
    const bStatsJson = await bStats.json() as {
      yesterday: unknown;
      personalBest: unknown;
      last7Days: unknown[];
    };
    expect(bStatsJson.personalBest).toBeNull();
    expect(bStatsJson.last7Days).toEqual([]);

    // A fetches /stats and DOES see their data (sanity).
    const aStats = await authedGet(app, '/api/v1/workouts/stats', a.token);
    const aStatsJson = await aStats.json() as {
      personalBest: { reps: number } | null;
      last7Days: unknown[];
    };
    expect(aStatsJson.personalBest).not.toBeNull();
    expect(aStatsJson.personalBest?.reps).toBe(13);
    expect(aStatsJson.last7Days.length).toBeGreaterThan(0);
  });

  it('a weekly plan generated by A is not returned to B', async () => {
    const { app, db } = buildApp();
    const a = await register(app);
    const b = await register(app);

    // A generates a weekly plan — inserts into weekly_plans with A's device_id.
    const aPlanRes = await authedJson(app, '/api/v1/plan/weekly', a.token, { exerciseId: 'pushups' });
    expect(aPlanRes.status).toBe(200);
    const aPlan = await aPlanRes.json() as { id: string };
    expect(aPlan.id).toBeTruthy();

    // B generates a plan. The "previous plan" query inside the route must
    // not surface A's plan. We assert that by counting rows scoped to each
    // device after both calls have run.
    const bPlanRes = await authedJson(app, '/api/v1/plan/weekly', b.token, { exerciseId: 'pushups' });
    expect(bPlanRes.status).toBe(200);

    const aRows = db.prepare(`SELECT id FROM weekly_plans WHERE device_id = ?`).all(a.deviceId) as Array<{ id: string }>;
    const bRows = db.prepare(`SELECT id FROM weekly_plans WHERE device_id = ?`).all(b.deviceId) as Array<{ id: string }>;
    expect(aRows.length).toBe(1);
    expect(bRows.length).toBe(1);
    expect(aRows[0].id).not.toBe(bRows[0].id);
  });

  it('swapping bearer tokens swaps the visible /stats data', async () => {
    const { app } = buildApp();
    const a = await register(app);
    const b = await register(app);

    const startedAt = new Date(Date.now() - 3 * 60 * 60 * 1000).toISOString();

    await authedJson(app, '/api/v1/workouts/sync', a.token, {
      sessions: [makeSession('sess-a-only', startedAt)],
    });
    await authedJson(app, '/api/v1/workouts/sync', b.token, {
      sessions: [
        { ...makeSession('sess-b-only', startedAt), sets: [
          { id: 'sess-b-only-s1', setNumber: 1, reps: 99, recordedAt: startedAt, restSeconds: null },
        ] },
      ],
    });

    const aStats = await (await authedGet(app, '/api/v1/workouts/stats', a.token)).json() as {
      personalBest: { reps: number } | null;
    };
    const bStats = await (await authedGet(app, '/api/v1/workouts/stats', b.token)).json() as {
      personalBest: { reps: number } | null;
    };

    // A sees max rep 13 from their own session; never 99 (B's set).
    expect(aStats.personalBest?.reps).toBe(13);
    // B sees max rep 99 from their own set; never 13 (A's set).
    expect(bStats.personalBest?.reps).toBe(99);
  });

  it("server stamps device_id from Bearer; client-supplied deviceId in body is ignored", async () => {
    const { app, db } = buildApp();
    const a = await register(app);
    const b = await register(app);

    const startedAt = new Date(Date.now() - 1 * 60 * 60 * 1000).toISOString();

    // A authenticates but tries to spoof B's deviceId in the body.
    const res = await app.request('/api/v1/workouts/sync', {
      method: 'POST',
      headers: { 'Content-Type': 'application/json', Authorization: `Bearer ${a.token}` },
      body: JSON.stringify({
        deviceId: b.deviceId, // ignored
        sessions: [makeSession('sess-spoof', startedAt)],
      }),
    });
    expect(res.status).toBe(200);

    // The row must be stamped with A's deviceId, not B's.
    const row = db.prepare(`SELECT device_id FROM sessions WHERE id = ?`).get('sess-spoof') as { device_id: string };
    expect(row.device_id).toBe(a.deviceId);
    expect(row.device_id).not.toBe(b.deviceId);
  });
});
